REPORT  ztms_analyse.

INCLUDE ZTMS_ANALYSE_TOP.
INCLUDE ZTMS_ANALYSE_ALV100.
INCLUDE ZTMS_ANALYSE_ALV300.
INCLUDE ZTMS_ANALYSE_SCR.
INCLUDE ZTMS_ANALYSE_FRM.
INCLUDE ZTMS_ANALYSE_PBO.
INCLUDE ZTMS_ANALYSE_PAI.

START-OF-SELECTION.
  PERFORM init.

END-OF-SELECTION.

  PERFORM alv.
